// Code generated by MockGen. DO NOT EDIT.
// Source: remove.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/AlexeyGribchenko/task-tracker-cli/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskRemover is a mock of TaskRemover interface.
type MockTaskRemover struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRemoverMockRecorder
}

// MockTaskRemoverMockRecorder is the mock recorder for MockTaskRemover.
type MockTaskRemoverMockRecorder struct {
	mock *MockTaskRemover
}

// NewMockTaskRemover creates a new mock instance.
func NewMockTaskRemover(ctrl *gomock.Controller) *MockTaskRemover {
	mock := &MockTaskRemover{ctrl: ctrl}
	mock.recorder = &MockTaskRemoverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRemover) EXPECT() *MockTaskRemoverMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTaskRemover) Execute(input dto.RemoveTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockTaskRemoverMockRecorder) Execute(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTaskRemover)(nil).Execute), input)
}

// MockSuccesWriter is a mock of SuccesWriter interface.
type MockSuccesWriter struct {
	ctrl     *gomock.Controller
	recorder *MockSuccesWriterMockRecorder
}

// MockSuccesWriterMockRecorder is the mock recorder for MockSuccesWriter.
type MockSuccesWriterMockRecorder struct {
	mock *MockSuccesWriter
}

// NewMockSuccesWriter creates a new mock instance.
func NewMockSuccesWriter(ctrl *gomock.Controller) *MockSuccesWriter {
	mock := &MockSuccesWriter{ctrl: ctrl}
	mock.recorder = &MockSuccesWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuccesWriter) EXPECT() *MockSuccesWriterMockRecorder {
	return m.recorder
}

// PrintSuccessMessage mocks base method.
func (m *MockSuccesWriter) PrintSuccessMessage(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintSuccessMessage", message)
}

// PrintSuccessMessage indicates an expected call of PrintSuccessMessage.
func (mr *MockSuccesWriterMockRecorder) PrintSuccessMessage(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintSuccessMessage", reflect.TypeOf((*MockSuccesWriter)(nil).PrintSuccessMessage), message)
}
