// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/AlexeyGribchenko/task-tracker-cli/internal/domain"
	dto "github.com/AlexeyGribchenko/task-tracker-cli/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskCreator is a mock of TaskCreator interface.
type MockTaskCreator struct {
	ctrl     *gomock.Controller
	recorder *MockTaskCreatorMockRecorder
}

// MockTaskCreatorMockRecorder is the mock recorder for MockTaskCreator.
type MockTaskCreatorMockRecorder struct {
	mock *MockTaskCreator
}

// NewMockTaskCreator creates a new mock instance.
func NewMockTaskCreator(ctrl *gomock.Controller) *MockTaskCreator {
	mock := &MockTaskCreator{ctrl: ctrl}
	mock.recorder = &MockTaskCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskCreator) EXPECT() *MockTaskCreatorMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskCreator) CreateTask(task domain.Task) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", task)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskCreatorMockRecorder) CreateTask(task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskCreator)(nil).CreateTask), task)
}

// MockTaskUpdater is a mock of TaskUpdater interface.
type MockTaskUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockTaskUpdaterMockRecorder
}

// MockTaskUpdaterMockRecorder is the mock recorder for MockTaskUpdater.
type MockTaskUpdaterMockRecorder struct {
	mock *MockTaskUpdater
}

// NewMockTaskUpdater creates a new mock instance.
func NewMockTaskUpdater(ctrl *gomock.Controller) *MockTaskUpdater {
	mock := &MockTaskUpdater{ctrl: ctrl}
	mock.recorder = &MockTaskUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskUpdater) EXPECT() *MockTaskUpdaterMockRecorder {
	return m.recorder
}

// UpdateTaskStatus mocks base method.
func (m *MockTaskUpdater) UpdateTaskStatus(id int, status domain.TaskStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockTaskUpdaterMockRecorder) UpdateTaskStatus(id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockTaskUpdater)(nil).UpdateTaskStatus), id, status)
}

// MockTaskGetter is a mock of TaskGetter interface.
type MockTaskGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTaskGetterMockRecorder
}

// MockTaskGetterMockRecorder is the mock recorder for MockTaskGetter.
type MockTaskGetterMockRecorder struct {
	mock *MockTaskGetter
}

// NewMockTaskGetter creates a new mock instance.
func NewMockTaskGetter(ctrl *gomock.Controller) *MockTaskGetter {
	mock := &MockTaskGetter{ctrl: ctrl}
	mock.recorder = &MockTaskGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskGetter) EXPECT() *MockTaskGetterMockRecorder {
	return m.recorder
}

// GetTasks mocks base method.
func (m *MockTaskGetter) GetTasks() ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks")
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockTaskGetterMockRecorder) GetTasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockTaskGetter)(nil).GetTasks))
}

// MockTaskRemover is a mock of TaskRemover interface.
type MockTaskRemover struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRemoverMockRecorder
}

// MockTaskRemoverMockRecorder is the mock recorder for MockTaskRemover.
type MockTaskRemoverMockRecorder struct {
	mock *MockTaskRemover
}

// NewMockTaskRemover creates a new mock instance.
func NewMockTaskRemover(ctrl *gomock.Controller) *MockTaskRemover {
	mock := &MockTaskRemover{ctrl: ctrl}
	mock.recorder = &MockTaskRemoverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRemover) EXPECT() *MockTaskRemoverMockRecorder {
	return m.recorder
}

// RemoveTask mocks base method.
func (m *MockTaskRemover) RemoveTask(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTask", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTask indicates an expected call of RemoveTask.
func (mr *MockTaskRemoverMockRecorder) RemoveTask(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTask", reflect.TypeOf((*MockTaskRemover)(nil).RemoveTask), id)
}

// MockTaskSortedGetter is a mock of TaskSortedGetter interface.
type MockTaskSortedGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTaskSortedGetterMockRecorder
}

// MockTaskSortedGetterMockRecorder is the mock recorder for MockTaskSortedGetter.
type MockTaskSortedGetterMockRecorder struct {
	mock *MockTaskSortedGetter
}

// NewMockTaskSortedGetter creates a new mock instance.
func NewMockTaskSortedGetter(ctrl *gomock.Controller) *MockTaskSortedGetter {
	mock := &MockTaskSortedGetter{ctrl: ctrl}
	mock.recorder = &MockTaskSortedGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskSortedGetter) EXPECT() *MockTaskSortedGetterMockRecorder {
	return m.recorder
}

// GetSorted mocks base method.
func (m *MockTaskSortedGetter) GetSorted(columnName domain.ColumnTitle) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSorted", columnName)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSorted indicates an expected call of GetSorted.
func (mr *MockTaskSortedGetterMockRecorder) GetSorted(columnName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSorted", reflect.TypeOf((*MockTaskSortedGetter)(nil).GetSorted), columnName)
}

// MockTaskFilteredGetter is a mock of TaskFilteredGetter interface.
type MockTaskFilteredGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTaskFilteredGetterMockRecorder
}

// MockTaskFilteredGetterMockRecorder is the mock recorder for MockTaskFilteredGetter.
type MockTaskFilteredGetterMockRecorder struct {
	mock *MockTaskFilteredGetter
}

// NewMockTaskFilteredGetter creates a new mock instance.
func NewMockTaskFilteredGetter(ctrl *gomock.Controller) *MockTaskFilteredGetter {
	mock := &MockTaskFilteredGetter{ctrl: ctrl}
	mock.recorder = &MockTaskFilteredGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskFilteredGetter) EXPECT() *MockTaskFilteredGetterMockRecorder {
	return m.recorder
}

// GetFiltered mocks base method.
func (m *MockTaskFilteredGetter) GetFiltered(columnName domain.ColumnTitle, filterValue string) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFiltered", columnName, filterValue)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFiltered indicates an expected call of GetFiltered.
func (mr *MockTaskFilteredGetterMockRecorder) GetFiltered(columnName, filterValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFiltered", reflect.TypeOf((*MockTaskFilteredGetter)(nil).GetFiltered), columnName, filterValue)
}

// MockGetTasksUseCase is a mock of GetTasksUseCase interface.
type MockGetTasksUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTasksUseCaseMockRecorder
}

// MockGetTasksUseCaseMockRecorder is the mock recorder for MockGetTasksUseCase.
type MockGetTasksUseCaseMockRecorder struct {
	mock *MockGetTasksUseCase
}

// NewMockGetTasksUseCase creates a new mock instance.
func NewMockGetTasksUseCase(ctrl *gomock.Controller) *MockGetTasksUseCase {
	mock := &MockGetTasksUseCase{ctrl: ctrl}
	mock.recorder = &MockGetTasksUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTasksUseCase) EXPECT() *MockGetTasksUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetTasksUseCase) Execute(input dto.GetTaskList) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetTasksUseCaseMockRecorder) Execute(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetTasksUseCase)(nil).Execute), input)
}

// MockCreateTaskUseCase is a mock of CreateTaskUseCase interface.
type MockCreateTaskUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTaskUseCaseMockRecorder
}

// MockCreateTaskUseCaseMockRecorder is the mock recorder for MockCreateTaskUseCase.
type MockCreateTaskUseCaseMockRecorder struct {
	mock *MockCreateTaskUseCase
}

// NewMockCreateTaskUseCase creates a new mock instance.
func NewMockCreateTaskUseCase(ctrl *gomock.Controller) *MockCreateTaskUseCase {
	mock := &MockCreateTaskUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateTaskUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateTaskUseCase) EXPECT() *MockCreateTaskUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateTaskUseCase) Execute(input dto.CreateTask) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateTaskUseCaseMockRecorder) Execute(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateTaskUseCase)(nil).Execute), input)
}

// MockUpdateTaskStatusUseCase is a mock of UpdateTaskStatusUseCase interface.
type MockUpdateTaskStatusUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateTaskStatusUseCaseMockRecorder
}

// MockUpdateTaskStatusUseCaseMockRecorder is the mock recorder for MockUpdateTaskStatusUseCase.
type MockUpdateTaskStatusUseCaseMockRecorder struct {
	mock *MockUpdateTaskStatusUseCase
}

// NewMockUpdateTaskStatusUseCase creates a new mock instance.
func NewMockUpdateTaskStatusUseCase(ctrl *gomock.Controller) *MockUpdateTaskStatusUseCase {
	mock := &MockUpdateTaskStatusUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateTaskStatusUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateTaskStatusUseCase) EXPECT() *MockUpdateTaskStatusUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateTaskStatusUseCase) Execute(input dto.UpdateTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateTaskStatusUseCaseMockRecorder) Execute(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateTaskStatusUseCase)(nil).Execute), input)
}

// MockRemoveTaskUseCase is a mock of RemoveTaskUseCase interface.
type MockRemoveTaskUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRemoveTaskUseCaseMockRecorder
}

// MockRemoveTaskUseCaseMockRecorder is the mock recorder for MockRemoveTaskUseCase.
type MockRemoveTaskUseCaseMockRecorder struct {
	mock *MockRemoveTaskUseCase
}

// NewMockRemoveTaskUseCase creates a new mock instance.
func NewMockRemoveTaskUseCase(ctrl *gomock.Controller) *MockRemoveTaskUseCase {
	mock := &MockRemoveTaskUseCase{ctrl: ctrl}
	mock.recorder = &MockRemoveTaskUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoveTaskUseCase) EXPECT() *MockRemoveTaskUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRemoveTaskUseCase) Execute(input dto.RemoveTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockRemoveTaskUseCaseMockRecorder) Execute(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRemoveTaskUseCase)(nil).Execute), input)
}
