// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/AlexeyGribchenko/task-tracker-cli/internal/domain"
	dto "github.com/AlexeyGribchenko/task-tracker-cli/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskRepository) CreateTask(task domain.Task) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", task)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskRepositoryMockRecorder) CreateTask(task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskRepository)(nil).CreateTask), task)
}

// GetTasks mocks base method.
func (m *MockTaskRepository) GetTasks() ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks")
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockTaskRepositoryMockRecorder) GetTasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockTaskRepository)(nil).GetTasks))
}

// UpdateTaskStatus mocks base method.
func (m *MockTaskRepository) UpdateTaskStatus(id int, status domain.TaskStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockTaskRepositoryMockRecorder) UpdateTaskStatus(id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTaskStatus), id, status)
}

// MockGetTasksUseCase is a mock of GetTasksUseCase interface.
type MockGetTasksUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTasksUseCaseMockRecorder
}

// MockGetTasksUseCaseMockRecorder is the mock recorder for MockGetTasksUseCase.
type MockGetTasksUseCaseMockRecorder struct {
	mock *MockGetTasksUseCase
}

// NewMockGetTasksUseCase creates a new mock instance.
func NewMockGetTasksUseCase(ctrl *gomock.Controller) *MockGetTasksUseCase {
	mock := &MockGetTasksUseCase{ctrl: ctrl}
	mock.recorder = &MockGetTasksUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTasksUseCase) EXPECT() *MockGetTasksUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetTasksUseCase) Execute() ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetTasksUseCaseMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetTasksUseCase)(nil).Execute))
}

// MockCreateTaskUseCase is a mock of CreateTaskUseCase interface.
type MockCreateTaskUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTaskUseCaseMockRecorder
}

// MockCreateTaskUseCaseMockRecorder is the mock recorder for MockCreateTaskUseCase.
type MockCreateTaskUseCaseMockRecorder struct {
	mock *MockCreateTaskUseCase
}

// NewMockCreateTaskUseCase creates a new mock instance.
func NewMockCreateTaskUseCase(ctrl *gomock.Controller) *MockCreateTaskUseCase {
	mock := &MockCreateTaskUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateTaskUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateTaskUseCase) EXPECT() *MockCreateTaskUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateTaskUseCase) Execute(input dto.CreateTask) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateTaskUseCaseMockRecorder) Execute(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateTaskUseCase)(nil).Execute), input)
}

// MockUpdateTaskStatusUseCase is a mock of UpdateTaskStatusUseCase interface.
type MockUpdateTaskStatusUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateTaskStatusUseCaseMockRecorder
}

// MockUpdateTaskStatusUseCaseMockRecorder is the mock recorder for MockUpdateTaskStatusUseCase.
type MockUpdateTaskStatusUseCaseMockRecorder struct {
	mock *MockUpdateTaskStatusUseCase
}

// NewMockUpdateTaskStatusUseCase creates a new mock instance.
func NewMockUpdateTaskStatusUseCase(ctrl *gomock.Controller) *MockUpdateTaskStatusUseCase {
	mock := &MockUpdateTaskStatusUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateTaskStatusUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateTaskStatusUseCase) EXPECT() *MockUpdateTaskStatusUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateTaskStatusUseCase) Execute(input dto.UpdateTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateTaskStatusUseCaseMockRecorder) Execute(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateTaskStatusUseCase)(nil).Execute), input)
}
