// Code generated by MockGen. DO NOT EDIT.
// Source: list.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/AlexeyGribchenko/task-tracker-cli/internal/domain"
	dto "github.com/AlexeyGribchenko/task-tracker-cli/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskWriter is a mock of TaskWriter interface.
type MockTaskWriter struct {
	ctrl     *gomock.Controller
	recorder *MockTaskWriterMockRecorder
}

// MockTaskWriterMockRecorder is the mock recorder for MockTaskWriter.
type MockTaskWriterMockRecorder struct {
	mock *MockTaskWriter
}

// NewMockTaskWriter creates a new mock instance.
func NewMockTaskWriter(ctrl *gomock.Controller) *MockTaskWriter {
	mock := &MockTaskWriter{ctrl: ctrl}
	mock.recorder = &MockTaskWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskWriter) EXPECT() *MockTaskWriterMockRecorder {
	return m.recorder
}

// RenderTable mocks base method.
func (m *MockTaskWriter) RenderTable(tasks []domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderTable", tasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenderTable indicates an expected call of RenderTable.
func (mr *MockTaskWriterMockRecorder) RenderTable(tasks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderTable", reflect.TypeOf((*MockTaskWriter)(nil).RenderTable), tasks)
}

// MockTasksGetter is a mock of TasksGetter interface.
type MockTasksGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTasksGetterMockRecorder
}

// MockTasksGetterMockRecorder is the mock recorder for MockTasksGetter.
type MockTasksGetterMockRecorder struct {
	mock *MockTasksGetter
}

// NewMockTasksGetter creates a new mock instance.
func NewMockTasksGetter(ctrl *gomock.Controller) *MockTasksGetter {
	mock := &MockTasksGetter{ctrl: ctrl}
	mock.recorder = &MockTasksGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTasksGetter) EXPECT() *MockTasksGetterMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTasksGetter) Execute(input dto.GetTaskList) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockTasksGetterMockRecorder) Execute(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTasksGetter)(nil).Execute), input)
}
