// Code generated by MockGen. DO NOT EDIT.
// Source: update.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/AlexeyGribchenko/task-tracker-cli/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskUpdater is a mock of TaskUpdater interface.
type MockTaskUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockTaskUpdaterMockRecorder
}

// MockTaskUpdaterMockRecorder is the mock recorder for MockTaskUpdater.
type MockTaskUpdaterMockRecorder struct {
	mock *MockTaskUpdater
}

// NewMockTaskUpdater creates a new mock instance.
func NewMockTaskUpdater(ctrl *gomock.Controller) *MockTaskUpdater {
	mock := &MockTaskUpdater{ctrl: ctrl}
	mock.recorder = &MockTaskUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskUpdater) EXPECT() *MockTaskUpdaterMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTaskUpdater) Execute(input dto.UpdateTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockTaskUpdaterMockRecorder) Execute(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTaskUpdater)(nil).Execute), input)
}

// MockSuccesWriter is a mock of SuccesWriter interface.
type MockSuccesWriter struct {
	ctrl     *gomock.Controller
	recorder *MockSuccesWriterMockRecorder
}

// MockSuccesWriterMockRecorder is the mock recorder for MockSuccesWriter.
type MockSuccesWriterMockRecorder struct {
	mock *MockSuccesWriter
}

// NewMockSuccesWriter creates a new mock instance.
func NewMockSuccesWriter(ctrl *gomock.Controller) *MockSuccesWriter {
	mock := &MockSuccesWriter{ctrl: ctrl}
	mock.recorder = &MockSuccesWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuccesWriter) EXPECT() *MockSuccesWriterMockRecorder {
	return m.recorder
}

// PrintSuccessMessage mocks base method.
func (m *MockSuccesWriter) PrintSuccessMessage(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintSuccessMessage", message)
}

// PrintSuccessMessage indicates an expected call of PrintSuccessMessage.
func (mr *MockSuccesWriterMockRecorder) PrintSuccessMessage(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintSuccessMessage", reflect.TypeOf((*MockSuccesWriter)(nil).PrintSuccessMessage), message)
}
