// Code generated by MockGen. DO NOT EDIT.
// Source: create.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/AlexeyGribchenko/task-tracker-cli/internal/domain"
	dto "github.com/AlexeyGribchenko/task-tracker-cli/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskCreator is a mock of TaskCreator interface.
type MockTaskCreator struct {
	ctrl     *gomock.Controller
	recorder *MockTaskCreatorMockRecorder
}

// MockTaskCreatorMockRecorder is the mock recorder for MockTaskCreator.
type MockTaskCreatorMockRecorder struct {
	mock *MockTaskCreator
}

// NewMockTaskCreator creates a new mock instance.
func NewMockTaskCreator(ctrl *gomock.Controller) *MockTaskCreator {
	mock := &MockTaskCreator{ctrl: ctrl}
	mock.recorder = &MockTaskCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskCreator) EXPECT() *MockTaskCreatorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTaskCreator) Execute(input dto.CreateTask) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockTaskCreatorMockRecorder) Execute(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTaskCreator)(nil).Execute), input)
}

// MockSuccesWriter is a mock of SuccesWriter interface.
type MockSuccesWriter struct {
	ctrl     *gomock.Controller
	recorder *MockSuccesWriterMockRecorder
}

// MockSuccesWriterMockRecorder is the mock recorder for MockSuccesWriter.
type MockSuccesWriterMockRecorder struct {
	mock *MockSuccesWriter
}

// NewMockSuccesWriter creates a new mock instance.
func NewMockSuccesWriter(ctrl *gomock.Controller) *MockSuccesWriter {
	mock := &MockSuccesWriter{ctrl: ctrl}
	mock.recorder = &MockSuccesWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuccesWriter) EXPECT() *MockSuccesWriterMockRecorder {
	return m.recorder
}

// PrintSuccessMessage mocks base method.
func (m *MockSuccesWriter) PrintSuccessMessage(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintSuccessMessage", message)
}

// PrintSuccessMessage indicates an expected call of PrintSuccessMessage.
func (mr *MockSuccesWriterMockRecorder) PrintSuccessMessage(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintSuccessMessage", reflect.TypeOf((*MockSuccesWriter)(nil).PrintSuccessMessage), message)
}
